name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/

      - name: Build
        - run: |
            npm i
            npm run publish-package-actions
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
